/**
 * GitHub Export Service
 * Generates a complete, standalone Next.js + Express project
 * from an app config — ready to push to GitHub.
 */

import { AppConfig, Entity, EntityField } from '../types/config';

export function generateFullProject(config: AppConfig, appSlug: string): Record<string, string> {
  const files: Record<string, string> = {};

  files['README.md'] = generateReadme(config, appSlug);
  files['.env.example'] = generateEnvExample(config);
  files['.gitignore'] = generateGitignore();
  files['package.json'] = generateRootPackage(config);
  files['API.md'] = generateApiDocs(config, appSlug);
  files['config.json'] = JSON.stringify(config, null, 2);

  // Backend files
  files['backend/package.json'] = generateBackendPackage();
  files['backend/src/index.ts'] = generateBackendIndex();
  files['backend/src/config.ts'] = `export const APP_CONFIG = ${JSON.stringify(config, null, 2)} as const;\n`;

  // Entity type definitions
  files['backend/src/types.ts'] = generateEntityTypes(config);

  // Frontend files
  files['frontend/package.json'] = generateFrontendPackage(config);
  files['frontend/src/config.ts'] = `export const APP_CONFIG = ${JSON.stringify(config, null, 2)} as const;\n`;

  // Docker
  files['docker-compose.yml'] = generateDockerCompose(appSlug);

  return files;
}

function generateReadme(config: AppConfig, slug: string): string {
  const entities = config.entities.map((e) =>
    `- **${e.name}** (${e.fields.filter((f) => !f.auto && !f.primary).length} fields)`
  ).join('\n');

  const pages = config.pages.map((p) => `- \`${p.path}\` — ${p.title}`).join('\n');

  return `# ${config.name}

${config.description || 'Generated by AppForge — config-driven app generator.'}

## Entities
${entities || '_(none)_'}

## Pages
${pages || '_(none)_'}

## Tech Stack
- **Frontend:** Next.js 14, React, Tailwind CSS
- **Backend:** Node.js, Express, TypeScript
- **Database:** PostgreSQL (JSONB records)
- **Auth:** JWT + ${config.auth?.methods?.join(' + ') || 'Email'}

## Quick Start

\`\`\`bash
cp .env.example .env
docker-compose up -d
\`\`\`

Or deploy to Railway + Vercel — see deployment docs.

## AppForge
Re-import \`config.json\` to [AppForge](https://appforge.dev) to regenerate or modify this app.

---
App slug: \`${slug}\`
Generated: ${new Date().toISOString().split('T')[0]}
`;
}

function generateEnvExample(config: AppConfig): string {
  const hasGoogle = config.auth?.methods?.includes('google');
  return `# Database
DATABASE_URL=postgresql://user:password@localhost:5432/${config.name.toLowerCase().replace(/\s+/g, '_')}

# Auth
JWT_SECRET=change-me-to-a-random-32-char-string

# App
FRONTEND_URL=http://localhost:3000
PORT=4000
NODE_ENV=development

${hasGoogle ? `# Google OAuth
GOOGLE_CLIENT_ID=your-google-oauth-client-id
GOOGLE_CLIENT_SECRET=your-google-oauth-client-secret
` : ''}
# Email (optional)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-password
`;
}

function generateGitignore(): string {
  return `node_modules/
.next/
dist/
.env
.env.local
uploads/
*.log
.DS_Store
`;
}

function generateRootPackage(config: AppConfig): string {
  return JSON.stringify({
    name: config.name.toLowerCase().replace(/\s+/g, '-'),
    version: config.version || '1.0.0',
    private: true,
    scripts: {
      dev: 'concurrently "pnpm --filter backend dev" "pnpm --filter frontend dev"',
      build: 'pnpm --filter backend build && pnpm --filter frontend build',
    },
    workspaces: ['backend', 'frontend'],
  }, null, 2);
}

function generateBackendPackage(): string {
  return JSON.stringify({
    name: 'backend',
    version: '1.0.0',
    scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', start: 'node dist/index.js' },
    dependencies: {
      '@prisma/client': '^5.10.0',
      bcryptjs: '^2.4.3',
      cors: '^2.8.5',
      express: '^4.18.2',
      jsonwebtoken: '^9.0.2',
      uuid: '^9.0.0',
      zod: '^3.22.4',
    },
    devDependencies: {
      '@types/express': '^4.17.21',
      '@types/bcryptjs': '^2.4.6',
      '@types/jsonwebtoken': '^9.0.5',
      '@types/uuid': '^9.0.7',
      prisma: '^5.10.0',
      tsx: '^4.7.0',
      typescript: '^5.3.3',
    },
  }, null, 2);
}

function generateFrontendPackage(config: AppConfig): string {
  return JSON.stringify({
    name: 'frontend',
    version: '1.0.0',
    scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    dependencies: {
      next: '14.1.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      '@tanstack/react-query': '^5.20.5',
      axios: '^1.6.7',
      recharts: '^2.12.0',
      'lucide-react': '^0.323.0',
      'tailwindcss': '^3.3.0',
      'react-hot-toast': '^2.4.1',
    },
  }, null, 2);
}

function generateBackendIndex(): string {
  return `import express from 'express';
import cors from 'cors';
import { APP_CONFIG } from './config';

const app = express();
app.use(cors());
app.use(express.json());

// Config endpoint
app.get('/api/config', (_, res) => res.json(APP_CONFIG));

// Health check
app.get('/health', (_, res) => res.json({ status: 'ok' }));

app.listen(process.env.PORT || 4000, () => {
  console.log(\`Server running on port \${process.env.PORT || 4000}\`);
  console.log(\`App: \${APP_CONFIG.name}\`);
});
`;
}

function generateEntityTypes(config: AppConfig): string {
  const typeMap: Record<string, string> = {
    string: 'string', text: 'string', number: 'number', integer: 'number',
    boolean: 'boolean', datetime: 'string', date: 'string', uuid: 'string',
    enum: 'string', json: 'unknown', file: 'string',
  };

  const interfaces = config.entities.map((entity) => {
    const fields = entity.fields
      .filter((f) => !f.auto || f.primary)
      .map((f) => {
        const tsType = f.type === 'enum' && f.options?.length
          ? f.options.map((o) => `'${o}'`).join(' | ')
          : typeMap[f.type] || 'unknown';
        const optional = !f.required && !f.primary ? '?' : '';
        return `  ${f.name}${optional}: ${tsType};`;
      })
      .join('\n');

    return `export interface ${entity.name} {\n${fields}\n}`;
  });

  return `// Auto-generated entity types from AppForge config\n// Do not edit manually\n\n${interfaces.join('\n\n')}\n`;
}

function generateApiDocs(config: AppConfig, slug: string): string {
  const baseUrl = '${BASE_URL}';
  const entityDocs = config.entities.map((entity) => {
    const fields = entity.fields
      .filter((f) => !f.auto)
      .map((f) => `  - \`${f.name}\` (\`${f.type}\`)${f.required ? ' **required**' : ''}${f.options ? ` — options: ${f.options.join(', ')}` : ''}`)
      .join('\n');

    return `### ${entity.name}

**Fields:**
${fields}

**Endpoints:**
\`\`\`
GET    /api/apps/${slug}/entities/${entity.name}/records         list (supports ?page, ?pageSize, ?search, ?sortBy, ?sortOrder)
POST   /api/apps/${slug}/entities/${entity.name}/records         create
GET    /api/apps/${slug}/entities/${entity.name}/records/:id     get one
PUT    /api/apps/${slug}/entities/${entity.name}/records/:id     update
DELETE /api/apps/${slug}/entities/${entity.name}/records/:id     delete
GET    /api/apps/${slug}/entities/${entity.name}/aggregate       aggregate (?aggregate=count|sum|avg&field=&groupBy=)
GET    /api/apps/${slug}/entities/${entity.name}/csv/export      CSV export
POST   /api/apps/${slug}/entities/${entity.name}/csv/upload      CSV upload (multipart/form-data, field: file)
POST   /api/apps/${slug}/entities/${entity.name}/csv/import/:id  confirm import (?columnMap={})
\`\`\`
`;
  });

  return `# ${config.name} — API Reference

## Base URL
\`\`\`
${baseUrl}
\`\`\`

## Authentication
All endpoints require a Bearer token:
\`\`\`
Authorization: Bearer <your_jwt_token>
\`\`\`

Get a token via:
- \`POST /api/auth/login\` → \`{ email, password }\`
- \`POST /api/auth/register\` → \`{ email, password, name? }\`
- \`GET  /api/auth/google\` → OAuth redirect

---

${entityDocs.join('\n---\n\n')}

## Auth Endpoints

\`\`\`
POST /api/auth/register    { email, password, name? }
POST /api/auth/login       { email, password }
GET  /api/auth/me          (requires auth)
PATCH /api/auth/me         { name? }
GET  /api/auth/google      Google OAuth
\`\`\`

## Notifications

\`\`\`
GET   /api/notifications
GET   /api/notifications/unread-count
PATCH /api/notifications/:id/read
PATCH /api/notifications/read-all
DELETE /api/notifications/:id
\`\`\`
`;
}

function generateDockerCompose(slug: string): string {
  return `version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: appforge
      POSTGRES_PASSWORD: appforge_secret
      POSTGRES_DB: appforge
    ports: ['5432:5432']
    volumes: [postgres_data:/var/lib/postgresql/data]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U appforge']
      interval: 5s
      retries: 5

  backend:
    build: { context: ./backend }
    depends_on: { postgres: { condition: service_healthy } }
    environment:
      DATABASE_URL: postgresql://appforge:appforge_secret@postgres:5432/appforge
      JWT_SECRET: change-me
      FRONTEND_URL: http://localhost:3000
      PORT: 4000
    ports: ['4000:4000']

  frontend:
    build: { context: ./frontend }
    depends_on: [backend]
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-me
    ports: ['3000:3000']

volumes:
  postgres_data:
`;
}
